Aplicación/APP-ADMIN/src/Entity/Contenido.php
<?php

namespace App\Entity;

use App\Repository\ContenidoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContenidoRepository::class)
 */
class Contenido
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", name="idContenido")
     */
    private $idContenido;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $TipoContenido;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $DescripcionContenido;

    /**
     * @ORM\Column(type="string")
     */
    private $EnlaceContenido;

    public function getId(): ?int
    {
        return $this->idContenido;
    }

    public function getTipoContenido(): ?string
    {
        return $this->TipoContenido;
    }

    public function setTipoContenido(string $TipoContenido): self
    {
        $this->TipoContenido = $TipoContenido;

        return $this;
    }

    public function getDescripcionContenido(): ?string
    {
        return $this->DescripcionContenido;
    }

    public function setDescripcionContenido(string $DescripcionContenido): self
    {
        $this->DescripcionContenido = $DescripcionContenido;

        return $this;
    }

    public function getEnlaceContenido(): ?string
    {
        return $this->EnlaceContenido;
    }

    public function setEnlaceContenido(string $EnlaceContenido): self
    {
        $this->EnlaceContenido = $EnlaceContenido;

        return $this;
    }
}

Aplicación/APP-ADMIN/src/Form/ContenidoType.php
<?php

namespace App\Form;

use App\Entity\Contenido;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContenidoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('TipoContenido')
            ->add('DescripcionContenido')
            ->add('EnlaceContenido', FileType::class, ['mapped' => false, 'required' => false] )
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contenido::class,
        ]);
    }
}

Aplicación/APP-ADMIN/src/Controller/ContenidoController.php
<?php

namespace App\Controller;

use App\Entity\Contenido;
use App\Form\ContenidoType;
use App\Repository\ContenidoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/contenido")
 */
class ContenidoController extends AbstractController
{
    /**
     * @Route("/", name="contenido_index", methods={"GET"})
     */
    public function index(ContenidoRepository $contenidoRepository): Response
    {
        return $this->render('contenido/index.html.twig', [
            'contenidos' => $contenidoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="contenido_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $contenido = new Contenido();
        $form = $this->createForm(ContenidoType::class, $contenido);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $EnlaceContenido = $form->get('EnlaceContenido')->getData();

            if ($EnlaceContenido) {
                $originalFilename = pathinfo($EnlaceContenido->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$EnlaceContenido->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $EnlaceContenido->move(
                        $this->getParameter('contenido_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $contenido->setEnlaceContenido($newFilename);
            }
            $entityManager->persist($contenido);
            $entityManager->flush();

            return $this->redirectToRoute('evento_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contenido/new.html.twig', [
            'contenido' => $contenido,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{idContenido}", name="contenido_show", methods={"GET"})
     */
    public function show(Contenido $contenido): Response
    {
        return $this->render('contenido/show.html.twig', [
            'contenido' => $contenido,
        ]);
    }

    /**
     * @Route("/{idContenido}/edit", name="contenido_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Contenido $contenido, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(ContenidoType::class, $contenido);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $EnlaceContenido = $form->get('EnlaceContenido')->getData();

            if ($EnlaceContenido) {
                $originalFilename = pathinfo($EnlaceContenido->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$EnlaceContenido->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $EnlaceContenido->move(
                        $this->getParameter('contenido_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $contenido->setEnlaceContenido($newFilename);
            }

            $entityManager->flush();

            return $this->redirectToRoute('evento_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contenido/edit.html.twig', [
            'contenido' => $contenido,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{idContenido}", name="contenido_delete", methods={"POST"})
     */
    public function delete(Request $request, Contenido $contenido, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contenido->getId(), $request->request->get('_token'))) {
            $entityManager->remove($contenido);
            $entityManager->flush();
        }

        return $this->redirectToRoute('evento_index', [], Response::HTTP_SEE_OTHER);
    }
}

Aplicación/APP-ADMIN/templates/contenido/_delete_form.html.twig
<form method="post" action="{{ path('contenido_delete', {'idContenido': contenido.id}) }}" onsubmit="return confirm('¿Segura de que quieres eliminar?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contenido.id) }}">
    <button class="btn-blue">Eliminar</button>
</form>

Aplicación/APP-ADMIN/templates/contenido/_form.html.twig
<div data-aos="zoom-out-left">
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-danger">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}
</div>

Aplicación/APP-ADMIN/templates/contenido/edit.html.twig
{% extends "layout.html" %}

{% block content %}
    <h1>Editar Contenido</h1>

    {{ include('contenido/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('evento_index') }}">Volver a la lista</a>

    {{ include('contenido/_delete_form.html.twig') }}
{% endblock %}

Aplicación/APP-ADMIN/templates/contenido/index.html.twig
{% block title %}Contenido index{% endblock %}

{% block body %}
    <h1>Contenido index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>IdContenido</th>
                <th>TipoContenido</th>
                <th>DescripcionContenido</th>
                <th>EnlaceContenido</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contenido in contenidos %}
            <tr>
                <td>{{ contenido.id }}</td>
                <td>{{ contenido.TipoContenido }}</td>
                <td>{{ contenido.DescripcionContenido }}</td>
                <td>{{ contenido.EnlaceContenido }}</td>
                <td>
                    <a href="{{ path('contenido_show', {'idContenido': contenido.id}) }}">Ver</a>
                    <a href="{{ path('contenido_edit', {'idContenido': contenido.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('contenido_new') }}">Añadir</a>
{% endblock %}

Aplicación/APP-ADMIN/templates/contenido/new.html.twig
{% extends "layout.html" %}

{% block content %}
    <h1>Crear nuevo Contenido</h1>

    {{ include('contenido/_form.html.twig') }}

    <a href="{{ path('evento_index') }}">Volver a la lista</a>
{% endblock %}

Aplicación/APP-ADMIN/templates/contenido/show.html.twig
{% extends "layout.html" %}

{% block content %}
    <h1>Contenido</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>IdContenido</th>
                <td>{{ contenido.id }}</td>
            </tr>
            <tr>
                <th>TipoContenido</th>
                <td>{{ contenido.TipoContenido }}</td>
            </tr>
            <tr>
                <th>DescripcionContenido</th>
                <td>{{ contenido.DescripcionContenido }}</td>
            </tr>
            <tr>
                <th>EnlaceContenido</th>
                <td>{{ contenido.EnlaceContenido }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('evento_index') }}">Volver a la lista / </a>

    <a href="{{ path('contenido_edit', {'idContenido': contenido.id}) }}">Editar</a>

    {{ include('contenido/_delete_form.html.twig') }}
{% endblock %}